version: 2.1

jobs:
  test-build:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/.devops
            source .devops/bin/activate
            make install
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

  docker-build:
    docker:
      - image: circleci/python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17
          docker_layer_caching: true
      - run:
          name: Build docker container
          command: |
          docker build --tag=capstone_project
          # verify docker build
          docker image ls
      - run:
          name: Upload Docker image to Dockerhub
          command:
          echo $DOCKER_IMAGE_NAME



workflows:
  default:
    jobs:
      - test-build
      - docker-build